# Tells the travis we need to have sudo permission in order to have docker build
sudo: required
services: 
  - docker 

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

# all the commands needed to run our test suite
script:
  - docker run -e CI=true docker-react npm run test

#region is the same as the aws bean stalk, app name is aws application name
deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-112363934110"
  bucker_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
